### ISSUE TITLE
Support for Ollama API would be great

### ISSUE THREAD

**Issue by cheindel** [dotnet-smartcomponents/smartcomponents#17]
Ollama has an API that is compatible to the OpenAI API and lets me run LLMs locally.
However, if I change "Endpoint" in configuration to the appropriate local Ollama URL it does not work.
Please consider supporting Ollama, as due to the nature of the data being processed, I cannot use OpenAI in the cloud.

**Comment by SteveSandersonMS** [comment]
We can definitely do this. In fact by coincidence I was doing it myself yesterday.

One caveat though, is that the Ollama2 7B output is not very good for this, and probably not good enough to be usable in reality. I didn't try the bigger Ollama2 models - perhaps they are better. But Ollama2 7B's output was pretty weird on Smart Paste and Smart Textarea, compared with great quality results from gpt3.5-turbo (and gpt3.5-turbo is about 10x faster too).

I'd be very interested to know if you find bigger Ollama2 models behave better. More encouragingly, I did get quite good output from Mistral 7B (albeit still too slow on my dev machine's GPU).

**Comment by cheindel** [comment]
Give me the connectivity and I can try out different LLMs. 🤝

**Comment by cheindel** [comment]
At a first glance, autocompletion in German language using Sroecker/Sauerkrautlm-7b-Hero:Latest looks usable, running fast enough to be usable on a MacBook Pro M1 Max with 64 GB RAM. I will run some more tests including "Smart Paste" next week. Thank you for this initiative and and the fast response.
