### ISSUE TITLE
Source code of smartcomponents is missing

### ISSUE THREAD

**Issue by shahidmughal** [dotnet-smartcomponents/smartcomponents#20]
Very surprised to see the actual source code of smart components is missing.

**Comment by SteveSandersonMS** [comment]
Understood! Our short-term goal here is to understand whether or how these kinds of components would be useful to people. So if you can try them out and let us know if/how you would use them (or if not, why not, and what else would be needed) that would help us understand how to proceed. We only want to start maintaining a new open-source project once we understand that.

There's also another issue thread focused on this topic - https://github.com/dotnet-smartcomponents/smartcomponents/issues/13 - so I'll close this as a duplicate. Hope that's OK!
