### ISSUE TITLE
smartcomponents  - create an interface / adapter to use other AI services

### ISSUE THREAD

**Issue by ricardok1** [dotnet-smartcomponents/smartcomponents#21]
Hi @SteveSandersonMS 

Thanks for this initiative - keeps creating a good vibe around Blazor and in dotnet in general.

Please create an interface to be able to request any AI service. 
Any AI service should be able to create an "Adapter" and "dock" to smartcomponents. ;-)

Thanks
Ricardo

**Comment by SteveSandersonMS** [comment]
That's such a good idea that we already did it :) You can either:

 * Implement your own `IInferenceBackend` ([as mentioned in docs](https://github.com/dotnet-smartcomponents/smartcomponents/blob/main/docs/smart-paste.md#customizing-the-language-model-backend))
 * Or, use an OpenAI API-compatible endpoint like Ollama and [configure that as your endpoint](https://github.com/dotnet-smartcomponents/smartcomponents/blob/main/docs/configure-openai-backend.md#using-ollama-or-another-self-hosted-endpoint). This only shipped a few hours ago so make sure you're on the latest packages if you want to do that.

Note that none of the other backends I've yet found come close to the quality and speed of gpt-3.5-turbo, so make sure you also try that if you want the best results, and if you're trying to judge Smart Components as a whole.

**Comment by ricardok1** [comment]
Great work! Smart components are in one side and the AI inputs are another ;-)
