### ISSUE TITLE
Support multiple AI services?

### ISSUE THREAD

**Issue by davidpallmann** [dotnet-smartcomponents/smartcomponents#27]
Q. Can Smart Components be created that use any backing AI service, or are they restricted to Azure/OpenAI services only?

**Comment by SteveSandersonMS** [comment]
You can use any LLM backend you want.

You can either implement `IInferenceBackend` and write any logic you want to call a custom backing service, or you can use Ollama or similar by configuring it as described in https://github.com/dotnet-smartcomponents/smartcomponents/blob/main/docs/configure-openai-backend.md#using-ollama-or-another-self-hosted-endpoint.

Note that so far, gpt-3.5-turbo has been vastly more effective than any other model so please don't expect to get equivalent speed or quality from an arbitrarily chosen alternative model.
