### ISSUE TITLE
How Can I Set LocalEmbeddingsModelName and LocalEmbeddingsModelPath

### ISSUE THREAD

**Issue by yougdlek** [dotnet-smartcomponents/smartcomponents#33]
Hello, the component you made is working well.
Currently, I am in an offline environment and cannot download the model from the hugging face.

file path like this : "D:\\source\\repo\\ComponentTest\\wwwroot\\model.onnx"

I need to set the LocalEmbeddingsModelName and LocalEmbeddingsModelPath options. Can you help me on which file I should set them in?

**Comment by SteveSandersonMS** [comment]
In your .csproj file, add:

```xml
<PropertyGroup>
    <LocalEmbeddingsModelPath>full path to the model.onnx file</LocalEmbeddingsModelPath>
    <LocalEmbeddingsVocabPath>full path to the vocab.txt file</LocalEmbeddingsVocabPath>
</PropertyGroup>
```

That should do it but please let us know if not!
