### ISSUE TITLE
LocalEmbeddings do not work in a test project - `required file model.onnx does not exist` error

### ISSUE THREAD

**Issue by L-Sypniewski** [dotnet-smartcomponents/smartcomponents#37]
There's some issues with accessing/downloading models in test projects.
I have an xUnit test where I want to create embeddings and I'm getting the following error:

```
System.InvalidOperationException
Required file /Applications/Rider.app/Contents/lib/ReSharperHost/TestRunner/netcoreapp3.0/LocalEmbeddingsModel/default/model.onnx does not exist
   at SmartComponents.LocalEmbeddings.LocalEmbedder.GetFullPathToModelFile(String modelName, String fileName)
   at SmartComponents.LocalEmbeddings.LocalEmbedder..ctor(String modelName, Boolean caseSensitive)
   at LocalEmbeddingsTests.EmbeddingTests..ctor() in /Users/<myUsername>/Documents/developer/LocalEmbeddings/LocalEmbeddingsTests/EmbeddingTests.cs:line 12
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
```

Everything works fine in a Console app project

I use:
JetBrains Rider 2023.3.4
macOS Sonoma 14.3.1
SmartComponents.LocalEmbeddings version: 0.1.0-preview10146

**Comment by SteveSandersonMS** [comment]
Can you provide a repro project posted to GitHub?

The fact that your project path includes `netcoreapp3.0` makes it seem like you're running on .NET Core 3.0, which is not supported, and I don't know how you'd even have been able to install the package (since it requires `net6.0` or later). So I'm a bit confused :)

**Comment by L-Sypniewski** [comment]
Just in case - here's the repo: https://github.com/L-Sypniewski/SmartComponentsLocalEmbeddingsIssue

**Comment by SteveSandersonMS** [comment]
Can you upgrade to `0.1.0-preview10147` and try it now? It's now doing The Right Thing (tm) to locate the application files, so if it still doesn't work that would suggest a problem in the test runner. But hopefully it will work now.

**Comment by L-Sypniewski** [comment]
It works out-of-the-box in Rider after upgrading to `0.1.0-preview10147`.
Thank you for fixing it so quickly!
