### ISSUE TITLE
how can i  attach a domain specific llm?

### ISSUE THREAD

**Issue by curlyfro** [dotnet-smartcomponents/smartcomponents#40]
very cool but suppose my work is domain specific.  how can i  attach a domain specific llm?  is there a way for me to attach semantic kernel or[ langchain for .net](https://github.com/tryAGI/LangChain)?  this would give me choice of my backend

**Comment by SteveSandersonMS** [comment]
Yes, you can customize the inference in various ways:

 * You can use any other inference REST endpoint if it's compatible with OpenAI (e.g., Ollama): https://github.com/dotnet-smartcomponents/smartcomponents/blob/main/docs/configure-openai-backend.md#using-ollama-or-another-self-hosted-endpoint
 * You can implement `IInferenceBackend` in your .NET code and put in any logic you want to call your domain-specific LLM
 * You can subclass component-specific inference services and put in any logic you want to call your domain-specific LLM, e.g. https://github.com/dotnet-smartcomponents/smartcomponents/blob/main/docs/smart-paste.md#customizing-the-prompt
