### ISSUE TITLE
Localization issue

### ISSUE THREAD

**Issue by wullemsb** [dotnet-smartcomponents/smartcomponents#43]
When testing the Smart Combobox on my local machine, I never got any semantic matches back.

Further investigation showed that the minimal-threshold was incorrectly parsed due to my localization settings(nl-BE).
On my local machine 0.6f was parsed as 6 which is out of the range of supported values(0-1). 

In my language the decimal separator is a ',' (comma) and not a '.' (period).

I was able to work around the issue by explicitly setting the locale to en-US:

~~~~
var defaultCulture = "en-US";
var ci = new CultureInfo(defaultCulture);
app.UseRequestLocalization(new RequestLocalizationOptions
{
    DefaultRequestCulture = new RequestCulture("en-US"),
    SupportedCultures = new List<CultureInfo>
    {
        ci,
    },
    SupportedUICultures = new List<CultureInfo>
    {
        ci,
    }
});
~~~~

**Comment by SteveSandersonMS** [comment]
Interesting - thanks! Looks like we need to fix something in the parsing flow to ensure it uses culture-invariant parsing, so it will work regardless of your thread culture.

**Comment by wullemsb** [comment]
I'll upgrade and retry. Thanks already!
