### ISSUE TITLE
Build Issues 

### ISSUE THREAD

**Issue by darena-pjindal** [dotnet-smartcomponents/smartcomponents#45]
Hello - I downloaded the latest main branch and have updated it with my Open AI keys. I am getting the following error message when i try to build it. Is there a particular configuration that I need to use? 

 0>SmartComponents.LocalEmbeddings.targets(39,9): Error MSB3923 : Failed to download file "https://huggingface.co/SmartComponents/bge-micro-v2/resolve/72908b7/onnx/model_quantized.onnx".  The SSL connection could not be established, see inner exception. ---> Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.. ---> An existing connection was forcibly closed by the remote host.

**Comment by SteveSandersonMS** [comment]
@darena-pjindal I think that's a problem specific to your internet connection. I can definitely download the file from that URL. 

Maybe if you try again it will work now (if it was a temporary problem). Otherwise can you confirm whether or not you can download from that URL using your web browser?

**Comment by darena-pjindal** [comment]
> @darena-pjindal I think that's a problem specific to your internet connection. I can definitely download the file from that URL.
> 
> Maybe if you try again it will work now (if it was a temporary problem). Otherwise can you confirm whether or not you can download from that URL using your web browser?

 @SteveSandersonMS—Thanks so much for your reply. I confirmed that I am able to download that file directly. For some reason, it seems to be blocking it through the Nuget package. I will continue to check on my side as this looks like only an issue for me. Thanks again.
