### ISSUE TITLE
Consider using ITagHelperComponent for Tag Helper JavaScript

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet-smartcomponents/smartcomponents#5]
We could avoid the requirement that users add the `<smart-components-script />` element before the closing `</body>` tag by having the call to `builder.AddSmartComponents()` register an `ITagHelperComponent` implementation as [described here](https://learn.microsoft.com/aspnet/core/mvc/views/tag-helpers/th-components?view=aspnetcore-8.0#inject-into-html-body-element).

**Comment by SteveSandersonMS** [comment]
Oh cool, thanks! I'll do that.

**Comment by SteveSandersonMS** [comment]
Done
