### ISSUE TITLE
Specify model at runtime

### ISSUE THREAD

**Issue by Giorgi** [dotnet-smartcomponents/smartcomponents#54]
When using `LocalEmbedder` is it possible to specify the model to use at runtime (via ctor) instead of setting it in the csproj file? It can be useful when we want to experiment with different models and compare them.

**Comment by SteveSandersonMS** [comment]
Yes, the `LocalEmbedder` constructor already takes an optional `modelName` parameter.

You just need to make sure that you've already downloaded the model at build time (or to download it using your own logic at runtime before calling `new LocalEmbedder(modelName)`).
