### ISSUE TITLE
Open source the codebase

### ISSUE THREAD

**Issue by ledjon-behluli** [dotnet-smartcomponents/smartcomponents#57]
@SteveSandersonMS I know this has been raised in several other issues, but as you yourself have pointed out that it helps you guys if this is raised, as it shows that people are finding this project useful. I am specifically using the local embeddings. Anyhow, closing this now.

**Comment by SteveSandersonMS** [comment]
Thanks @ledjon-behluli! We are moving forwards with open-sourcing this at the moment. Hopefully in the next couple of weeks now.

**Comment by SteveSandersonMS** [comment]
BTW for local embeddings, support for that has now been added to Semantic Kernel so you might want to try that: https://github.com/dotnet/eShop/blob/72ad00d296572b78899213b2ed2d5a19bfae00b8/src/Catalog.API/Extensions/Extensions.cs#L34

**Comment by ledjon-behluli** [comment]
Interesting, thanks for pointing this out 🙂
